# Generated by Django 4.1.1 on 2022-10-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fields',
            options={'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
    ]
