# Generated by Django 4.1.1 on 2022-10-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_fields_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='status',
            field=models.CharField(choices=[('ac', 'Post is active'), ('de', 'Post is deactivated')], max_length=2),
        ),
        migrations.AlterField(
            model_name='fields',
            name='type',
            field=models.CharField(choices=[('bu', 'this post for Business'), ('pr', 'it’s Private post')], max_length=2),
        ),
    ]
