# Generated by Django 4.1.1 on 2022-10-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_fields_status_alter_fields_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Post is active'), ('DEACTIVATED', 'Post is deactivated')], max_length=11, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='type',
            field=models.CharField(choices=[('BUSINESS', 'This post for Business'), ('PRIVATE', 'It’s Private post')], max_length=8, verbose_name='Type'),
        ),
    ]
