# Generated by Django 4.1.1 on 2022-11-01 21:13

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_fields_status_alter_fields_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[posts.validators.validate_image]),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.ManyToManyField(to='posts.fields')),
            ],
        ),
    ]
