# Generated by Django 4.1.1 on 2022-11-05 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_fields_user_wishlist_delete_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fields',
            new_name='Post',
        ),
    ]
